#!/bin/bash

rm -rf ~/.local/share/Steam/steamapps/common/Sunrider\ 4\ The\ Captain\'s\ Return/backup &&

mkdir ~/.local/share/Steam/steamapps/common/Sunrider\ 4\ The\ Captain\'s\ Return/backup &&

cp -r ~/.local/share/Steam/steamapps/compatdata/2251620/pfx/drive_c/users/steamuser/AppData/Local/Sunrider_4_The_Captains_Return/saves ~/.local/share/Steam/steamapps/common/Sunrider\ 4\ The\ Captain\'s\ Return/backup/saves &&

cp ~/.local/share/Steam/steamapps/compatdata/2251620/pfx/drive_c/users/steamuser/AppData/Local/Sunrider_4_The_Captains_Return/seen.txt ~/.local/share/Steam/steamapps/common/Sunrider\ 4\ The\ Captain\'s\ Return/backup/seen.txt &&

cp ~/.local/share/Steam/steamapps/compatdata/2251620/pfx/drive_c/users/steamuser/AppData/Local/Sunrider_4_The_Captains_Return/init.ini ~/.local/share/Steam/steamapps/common/Sunrider\ 4\ The\ Captain\'s\ Return/backup/init.ini
