#!/bin/bash

GAME_FOLDER=$(find ~/ -name "Sunrider\ 4\ The\ Captain\'s\ Return" -path "*Steam/steamapps/common/*" -type d -print -quit)
PROGRESS_FOLDER=$(find ~/ -name "Sunrider_4_The_Captains_Return" -path "*Steam/steamapps/compatdata/2251620/pfx/drive_c/users/steamuser/AppData/Local/*" -type d -print -quit)
BACKUP_FOLDER="$GAME_FOLDER/backup/"
DATE=$(date +"%Y-%m-%d-%s")
BACKUP_FOLDER_BAK="$GAME_FOLDER/backup-bak_${DATE}"

mv "$BACKUP_FOLDER" "$BACKUP_FOLDER_BAK"

mkdir "$BACKUP_FOLDER"

cp -r "$PROGRESS_FOLDER/saves" "$BACKUP_FOLDER/"

cp "$PROGRESS_FOLDER/seen.txt" "$BACKUP_FOLDER/"

cp "$PROGRESS_FOLDER/init.ini" "$BACKUP_FOLDER/"
